App_Blog/urls.py
from django.urls import path
from App_Blog import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('create-blog/', views.CreateBlog.as_view(), name='create_blog'),
    path('blog_details/<str:slug>', views.blog_details, name='blog_details'),
    path('liked_post/<pk>/', views.liked, name='liked_post'),
    path('unliked_post/<pk>/', views.unliked, name='unliked_post'),
    path('my_blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit_blog/<pk>/', views.UpdateBlog.as_view(), name='edit_blog')
]

App_login/urls.py
from django.urls import path
from App_login import views


app_name = 'App_login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('user-change/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add-pro-pic/', views.add_pro_pic, name='add_pro_pic'),
    path('change-pro-pic/', views.change_pro_pic, name='change_pro_pic')
]

MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.Index, name='Index')
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5f98e371de.js" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title>{% block title_block %} Blogs {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item">
                <div class="container-fluid">
                    <a class="nav-item-active" href="{% url 'Index' %}"><img src="/media/profile_pics/logo.png" width="50px" class="rounded-circle"></a>
                </div>
            </li>
            {% if user.is_authenticated %}
            <div class=" dropdown">
                <a class="btn btn-primary dropdown-toggle" href="#" data-bs-toggle="dropdown">
                    @{{ user.username }}
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'App_Blog:create_blog' %}">Write Your Blog</a>
                    <a class="dropdown-item" href="{% url 'App_Blog:my_blogs' %}">My Blogs</a>
                    <a class="dropdown-item" href="{% url 'App_login:profile' %}">Your Profile</a>
                    <br>
                    <a class="dropdown-item" href="{% url 'App_login:logout' %}">Logout</a>
                </div>
            </div>
            {% else %}

            <li class="nav-item">
                <div class="container-fluid">
                    <a class="nav-item-active" href="{% url 'App_login:signup' %}">Sign Up</a>
                </div>
            </li>
            <li class="nav-item">
                <div class="container-fluid">
                    <a class="nav-item-active" href="{% url 'App_login:login' %}">Login</a>
                </div>
            </li>
            {% endif %}

        </ul>
    </nav>
    <div class="container" style="padding-top: 20px">
        {% block body_block %}

        {% endblock %}
    </div>

</body>
</html>